<a href="https://colab.research.google.com/github/V6388/work_on-_data-visualization-with-python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
n1=np.array([12,32,41,24])
n1

array([12, 32, 41, 24])

In [ ]:
n2=np.array([[54,32,45,67],[21,66,44,34]])
n2

array([[54, 32, 45, 67],
       [21, 66, 44, 34]])

In [ ]:
type(n1)

numpy.ndarray

In [ ]:
type(n2)

numpy.ndarray

In [ ]:
np3=np.zeros((2,2))
np3

array([[0., 0.],
       [0., 0.]])

In [ ]:
np4=np.zeros((5,5))
np4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
n1=np.full((2,2),10)
n1

array([[10, 10],
       [10, 10]])

In [ ]:
np1=np.arange(10,20)
np1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np1=np.arange(10,50,5)
np1

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
n1=np.random.randint(1,100,5)
n1

array([ 6, 39, 33,  5, 93])

In [ ]:
a=np.array([10,23])
b=np.array([12,34])
np.sum([a,b])

79

In [ ]:
np.sum([a,b],axis=0)

array([22, 57])

In [ ]:
np.sum([a,b],axis=1)


array([33, 46])

In [ ]:
n1=np.array([10,23,45,12])
n2=np.array([88,34,55,13])
np.vstack((n1,n2))

array([[10, 23, 45, 12],
       [88, 34, 55, 13]])

In [ ]:
np.hstack((n1,n2))

array([10, 23, 45, 12, 88, 34, 55, 13])

In [ ]:
np.column_stack((n1,n2))

array([[10, 88],
       [23, 34],
       [45, 55],
       [12, 13]])